### ISSUE TITLE
Uninstaller behaviour

### ISSUE THREAD

**Issue by ElektroQuark** [KiCad/kicad-winbuilder#27]
KiCad uninstaller doesn't delete Start menu entries.

**Comment by nickoe** [comment]
Which exact entries?

**Comment by ElektroQuark** [comment]
Hi Nick,

KiCad installer version: kicad-product-r6543.5349eb4-i686

Just installed:
![install](https://cloud.githubusercontent.com/assets/15322213/12916403/7e2ec536-cf32-11e5-85e1-680fe642c279.jpg)

After uninstall:
![uninstall](https://cloud.githubusercontent.com/assets/15322213/12916452/dc9d7ae0-cf32-11e5-87a6-18d3168c18a3.jpg)

**Comment by nickoe** [comment]
Please try the next nightly build.

**Comment by nickoe** [comment]
@ElektroQuark please try kicad-product-r6546.a319c34 from the nightlies.

**Comment by ElektroQuark** [comment]
It's solved. Last nightly build works OK.
Thanks Nick.

**Comment by nickoe** [comment]
Thank your for reporting :)
