### ISSUE TITLE
Installation fails when Windows username has multibyte character in it

### ISSUE THREAD

**Issue by Mamonbo** [KiCad/kicad-winbuilder#32]
I'm trying to build kicad on Win 8-64bit. make_x86_64.bat stopped leaving following message:
2>&1: line 0: cd: /MINGW-packages/mingw-w64-kicad-git: No such file or directory

Doing the same procedure as that of  "Windows username has space in it, which will cause issues with build process" in the readme.md,it seems that the makefile is working well.So,please add this case to the readme.md

**Comment by nickoe** [comment]
Please try to home alone branch for a workaround.
https://github.com/KiCad/kicad-winbuilder/tree/home_alone

**Comment by nickoe** [comment]
No response. Closing.
