### ISSUE TITLE
Windows Installer: text about Wing3D in the infobox after finishing the installation isn't complete readable

### ISSUE THREAD

**Issue by tijuca** [KiCad/kicad-winbuilder#46]
After a long time I installed the recent nightly amd64 version of the Windows version for KiCad. All went fine. Except the textbox about the indormation for the Wing3D package is to small or the text is to long. :-) Preferably the textbox needs to be more flexable as the available space in the box isn't used complete.

![windows_install_text_infobox2big](https://cloud.githubusercontent.com/assets/519979/21072758/8b38df06-becd-11e6-94bb-d09715983b6b.png)

**Comment by nickoe** [comment]
I think I would actually rather remove it. I don't think any one uses wings3d anymore and we suport iges and step models in the master branch now.

**Comment by easyw** [comment]
May be it would be useful to suggest FreeCAD both for VRML and STEP models... proven to be most compatible sw (same 3D mechanical kernel OCE), already used by many 3D developers, and open source too

Maurice

**Comment by tijuca** [comment]
Some kind of information about additional tools or software at this step in the installation is at least a good thing. But as people mostly an a "rush" at this point and don't get really noticed I would also put such a information in the info box (Help -> About KiCad) in the KiCad project manager. This must not be much or explicitly detailed, this could be done on the website of KiCad. There is really enough space to explain the various tools and technicals. Also there its probably easier to maintain downloads links and howtos. I still miss a easy guide to create basic 3D models and haven't found something actual

**Comment by nickoe** [comment]
What about simply removing it, does users ever click on stuff like that post install? It is only there because it was there before I adopted the installer.

But we might wat to add FreeCAD on http://kicad-pcb.org/external-tools/

**Comment by tijuca** [comment]
Then I would add some small information about additional external tools that can be found on that URL.
