### ISSUE TITLE
Error setting certificate verify locations and downloading kicad git repo

### ISSUE THREAD

**Issue by Teslafly** [KiCad/kicad-winbuilder#55]
On Windows 10 home x64

This is the issue I am having:

```
cd "C:/kicadwinbuild_dev/kicad-winbuilder/msys64/home/Marshall/MINGW-packages/mingw-w64-kicad-git" && export CARCH=x86_64 && TERM=vt220 makepkg-mingw -s --noconfirm
==> Making package: mingw-w64-x86_64-kicad-git r7029.cc2b358-1 (Tue, Nov 28, 2017  3:53:01 PM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning kicad git repo...
Cloning into bare repository '/home/Marshall/MINGW-packages/mingw-w64-kicad-git/kicad'...
fatal: unable to access 'https://github.com/KiCad/kicad-source-mirror.git/': error setting certificate verify locations:
  CAfile: /usr/ssl/certs/ca-bundle.crt
  CApath: none
==> ERROR: Failure while downloading kicad git repo
    Aborting...
```

This is after having an identical error, and manually running the git command to download the repo, which was a success. After I did that, it proceeded further and compiled some things, but then got stuck here again.

May be related to:[MSYS2-packages : git pull broken after system upgrade](https://github.com/Alexpux/MSYS2-packages/issues/998)

**Comment by nickoe** [comment]
I have been messing a bit around with this, but my internet connection is limited for the time being. But I think the cmake file needs to be patched to install p11-kit before it reinstall ca-certificates. Maybe we don't need to reinstall ca-certificates after the main update anymore.
