### ISSUE TITLE
How to Build KiCad

### ISSUE THREAD

**Issue by bvernoux** [KiCad/kicad-winbuilder#7]
A "How to Build KiCad" will be welcome and especially to find where the final binaries (installer ...) are ...
Anyway you have done an amazing work on this builder ! (I was previously using https://launchpad.net/kicad-winbuilder)

**Comment by nickoe** [comment]
Run one of the bat files, please feel free to test. It has actually been a long time since I used those directly, usually I just run makepkg-mingw and the copydlls.sh script.

**Comment by bvernoux** [comment]
I have tested by double clicking on **make_x86_64.bat** (from directory previously cloned with **git clone https://github.com/nickoe/KiCad-Winbuilder.git** using trunk SHA-1: 709a6b2c4c22c93880d4b9916b2377ca2d663d39)
Running bat file work to download & install msys and all dependencies in **KiCad-Winbuilder\msys64**.
I can see the build start and all seems fine except for the last steps to finalize the binaries ... (and the .bat windows just close without any error displayed).

In order to fix this I have done following steps:
- Double click on **KiCad-Winbuilder\msys64\msys2_shell.bat**
- **cd to KiCad-Winbuilder (root)**
- **cmake -Dx86_64=ON -P KiCad-Winbuilder.cmake**

And all is fine without any error and final binaries with installer are in
**KiCad-Winbuilder\msys64\home\UserName\out\pack-x86_64\**
With lot of directories and **kicad-product-r6248.20a3e23-x86_64.exe installer**

I think an update of https://github.com/nickoe/KiCad-Winbuilder/blob/master/readme.md or a Wiki page will be welcome for new user in order to build x86 & x64 version of kicad with installer from scratch

**Comment by nickoe** [comment]
Have you tried to execute `make_x86_64.bat` from the normal `cmd.exe` prompt? I am not sure that what you are trying to do is supposed to work.

**Comment by bvernoux** [comment]
Double clicking on .bat or launching it from cmd is the same (as the .bat will be executed in the same cmd environment), but I have not tested it, as it was solved using a real "linux" shell by using KiCad-Winbuilder\msys64\msys2_shell.bat which is really better than normal windows console which does not support color ...

**Comment by nickoe** [comment]
Yes indeed. But as according to the issue title, feel free tp create a pull request with description on how to use. I am a bit busy for the time being.

**Comment by FranzForstmayr** [comment]
I think i've triggered the same error now, but i don't know how to **cd to KiCad Winbuilder**, because the directory is above the **msys2_shell.bat**. Can you please explain what exactly you are doing?

**Comment by bvernoux** [comment]
To cd to to KiCad Winbuilder just use full path

Alternative way to build Kicad is clearly defined on official site to
http://kicad-pcb.org/contribute/build-windows/

**Comment by FranzForstmayr** [comment]
Thank you, 
I did not find this site before, maybe it should be linked to the dropdown menu of "Contribute" on the KiCad main page.

**Comment by nickoe** [comment]
Can we close this issue or?

**Comment by bvernoux** [comment]
Could you update the https://github.com/nickoe/KiCad-Winbuilder/blob/master/readme.md before to close ? (updating with a procedure with a how to a bit like it is done in this issue ?)

**Comment by bevanweiss** [comment]
There is a bit more of a 'how to' of building with the WinBuilder now.  I think this issue could be closed.

**Comment by bevanweiss** [comment]
There is a bit more of a 'how to' of building with the WinBuilder now.  I think this issue could be closed.
