### ISSUE TITLE
msys2-base-i686-20180531.tar.xz bad checksum

### ISSUE THREAD

**Issue by f6fvy** [KiCad/kicad-winbuilder#82]
Apparently, the md5 checksum of msys2-base-i686-20180531.tar.xz (used for 32-bit build environment) is wrong. I get b2ef7b785e49e5cec9de908c033107b5 instead of d41d8cd98f00b204e9800998ecf8427e (line 94 of KiCad-Winbuilder.cmake).

Can someone confirm and fix the script accordingly ?

**Comment by nickoe** [comment]
I see the same, but I have no idea of msys2 did a reupload or why the mismatch exist in the first place.

**Comment by nickoe** [comment]
@f6fvy I notice that it will always use the 64 bit base installer as a base on a 64 bit windows host. Maybe the checksum has been bad all the time.
